sudo: false
language: python
python:
- '2.7'
install: "./scripts/travis-setup.sh"
script: "./scripts/travis-test.sh"
addons:
  sauce_connect: true
env:
  global:
  - secure: Z7Y/PqrohQJydiq2ktrW+Z5RBN7/oadmInQhmJGyiiw8DzLbo4ogX16mURJrFJJBX8IZOtGZ/S3vMEN3yDvu7kzivUSDDOpbchIpZftnPdT5n+cU+XPvbNaTuXnrO8tZh4fewFBLuH55aXPi6x/kgu2l0z9W3LJQ+i9LpH86KXg= # SAUCE_USERNAME
  - secure: P05BokwVbGbEIuzI5ocW3i4D9QRF5iAH1yrpS/QcnfD4t2Knq/PvHTEdgDuKLLOb9B/LPRBy1ZMdOBhFTjQfVLJmVmWbCOEp/q/7tjFaOxaKRiWP81jbFCH50nCWuFPKP5YCThohD8oNPgPOrXcaD49hx/4+fSGA+oSedX/JhBE= # SAUCE_ACCESS_KEY
  - secure: FAyDpYkuBhDInLV9CjaSynkb9h2NP1xK+a9jmZnCzddj+guIebHTz1nWshqhNPR4WsJ9LeskpqGO6ke3lJDASlPWcQfe153I4XIR3J9WFF6y6pgsZxGoUBoB0AHBLvJHE2NWwknE2oJ7HtNRHTLBk53FgL95gmrSa6mTnvBUt7Q= # IMGUR_CLIENT_ID
